// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmqwlbqpgchzrmghjqlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttcXdsYnFwZ2NoenJtZ2hqcWx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NTQyMjgsImV4cCI6MjA2ODAzMDIyOH0.Cm9SUSIycpQ64BRzBuCN-AXm0jbX3U-nwYRvci9s0fA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});